addr: ":8080"
token_secret: "change-me"
token_ttl: "1h"
auth_provider: "local"
storage_backend: "memory"
postgres_dsn: ""
transport_key: ""
tls_enabled: false
tls_cert_file: ""
tls_key_file: ""
tls_ca_file: ""
keycloak:
  base_url: "http://localhost:8081"
  realm: "gophkeeper"
  client_id: "gophkeeper-cli"
  client_secret: ""
  admin_user: "admin"
  admin_password: "admin"
  admin_client_id: "admin-cli"
  admin_client_secret: ""
