// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package httpapi

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ChangeType.
const (
	Delete ChangeType = "delete"
	Upsert ChangeType = "upsert"
)

// Defines values for RecordType.
const (
	BankCard   RecordType = "bank_card"
	Binary     RecordType = "binary"
	Credential RecordType = "credential"
	Text       RecordType = "text"
)

// BankCardPayload defines model for BankCardPayload.
type BankCardPayload struct {
	Cardholder string     `json:"cardholder"`
	Cvv        string     `json:"cvv"`
	ExpiresAt  string     `json:"expires_at"`
	Kind       RecordType `json:"kind"`
	Number     string     `json:"number"`
}

// BinaryPayload defines model for BinaryPayload.
type BinaryPayload struct {
	Data []byte     `json:"data"`
	Kind RecordType `json:"kind"`
}

// ChangeType defines model for ChangeType.
type ChangeType string

// CredentialPayload defines model for CredentialPayload.
type CredentialPayload struct {
	Kind     RecordType `json:"kind"`
	Login    string     `json:"login"`
	Password string     `json:"password"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// Metadata defines model for Metadata.
type Metadata struct {
	Attributes  *map[string]string `json:"attributes,omitempty"`
	Description *string            `json:"description,omitempty"`
	Tags        *[]string          `json:"tags,omitempty"`
	Title       *string            `json:"title,omitempty"`
}

// Payload Record payload variant.
type Payload struct {
	union json.RawMessage
}

// PayloadBase defines model for PayloadBase.
type PayloadBase struct {
	Kind RecordType `json:"kind"`
}

// Record defines model for Record.
type Record struct {
	Id      string   `json:"id"`
	Meta    Metadata `json:"meta"`
	OwnerId string   `json:"owner_id"`

	// Payload Record payload variant.
	Payload   Payload    `json:"payload"`
	Type      RecordType `json:"type"`
	UpdatedAt time.Time  `json:"updated_at"`
	Version   int64      `json:"version"`
}

// RecordChange defines model for RecordChange.
type RecordChange struct {
	Change     ChangeType `json:"change"`
	HappenedAt time.Time  `json:"happened_at"`
	Meta       *Metadata  `json:"meta,omitempty"`
	OwnerId    string     `json:"owner_id"`

	// Payload Record payload variant.
	Payload  *Payload   `json:"payload,omitempty"`
	RecordId string     `json:"record_id"`
	Type     RecordType `json:"type"`
	Version  int64      `json:"version"`
}

// RecordType defines model for RecordType.
type RecordType string

// RecordUpsert defines model for RecordUpsert.
type RecordUpsert struct {
	Id   *string  `json:"id,omitempty"`
	Meta Metadata `json:"meta"`

	// Payload Record payload variant.
	Payload Payload    `json:"payload"`
	Type    RecordType `json:"type"`
	Version *int64     `json:"version,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// Session defines model for Session.
type Session struct {
	ExpiresAt time.Time `json:"expires_at"`
	Token     string    `json:"token"`
	UserId    string    `json:"user_id"`
}

// SyncBatch defines model for SyncBatch.
type SyncBatch struct {
	Changes []RecordChange `json:"changes"`
	Cursor  string         `json:"cursor"`
}

// SyncPush defines model for SyncPush.
type SyncPush struct {
	Changes []RecordChange `json:"changes"`
}

// SyncResult defines model for SyncResult.
type SyncResult struct {
	Applied   int32    `json:"applied"`
	Conflicts []string `json:"conflicts"`
	Rejected  int32    `json:"rejected"`
}

// TextPayload defines model for TextPayload.
type TextPayload struct {
	Kind RecordType `json:"kind"`
	Text string     `json:"text"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`
	Login     string    `json:"login"`
}

// ListRecordsParams defines parameters for ListRecords.
type ListRecordsParams struct {
	Type   *RecordType `form:"type,omitempty" json:"type,omitempty"`
	Tag    *string     `form:"tag,omitempty" json:"tag,omitempty"`
	Query  *string     `form:"query,omitempty" json:"query,omitempty"`
	Limit  *int32      `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int32      `form:"offset,omitempty" json:"offset,omitempty"`
}

// PullSyncParams defines parameters for PullSync.
type PullSyncParams struct {
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// UpsertRecordJSONRequestBody defines body for UpsertRecord for application/json ContentType.
type UpsertRecordJSONRequestBody = RecordUpsert

// PushSyncJSONRequestBody defines body for PushSync for application/json ContentType.
type PushSyncJSONRequestBody = SyncPush

// AsCredentialPayload returns the union data inside the Payload as a CredentialPayload
func (t Payload) AsCredentialPayload() (CredentialPayload, error) {
	var body CredentialPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCredentialPayload overwrites any union data inside the Payload as the provided CredentialPayload
func (t *Payload) FromCredentialPayload(v CredentialPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCredentialPayload performs a merge with any union data inside the Payload, using the provided CredentialPayload
func (t *Payload) MergeCredentialPayload(v CredentialPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTextPayload returns the union data inside the Payload as a TextPayload
func (t Payload) AsTextPayload() (TextPayload, error) {
	var body TextPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextPayload overwrites any union data inside the Payload as the provided TextPayload
func (t *Payload) FromTextPayload(v TextPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextPayload performs a merge with any union data inside the Payload, using the provided TextPayload
func (t *Payload) MergeTextPayload(v TextPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBinaryPayload returns the union data inside the Payload as a BinaryPayload
func (t Payload) AsBinaryPayload() (BinaryPayload, error) {
	var body BinaryPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBinaryPayload overwrites any union data inside the Payload as the provided BinaryPayload
func (t *Payload) FromBinaryPayload(v BinaryPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBinaryPayload performs a merge with any union data inside the Payload, using the provided BinaryPayload
func (t *Payload) MergeBinaryPayload(v BinaryPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBankCardPayload returns the union data inside the Payload as a BankCardPayload
func (t Payload) AsBankCardPayload() (BankCardPayload, error) {
	var body BankCardPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBankCardPayload overwrites any union data inside the Payload as the provided BankCardPayload
func (t *Payload) FromBankCardPayload(v BankCardPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBankCardPayload performs a merge with any union data inside the Payload, using the provided BankCardPayload
func (t *Payload) MergeBankCardPayload(v BankCardPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Payload) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Payload) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate a user
	// (POST /v1/auth/login)
	Login(c *gin.Context)
	// Register a new user
	// (POST /v1/auth/register)
	Register(c *gin.Context)
	// Validate an access token
	// (GET /v1/auth/validate)
	Validate(c *gin.Context)
	// List records
	// (GET /v1/records)
	ListRecords(c *gin.Context, params ListRecordsParams)
	// Create or update a record
	// (POST /v1/records)
	UpsertRecord(c *gin.Context)
	// Delete a record
	// (DELETE /v1/records/{id})
	DeleteRecord(c *gin.Context, id string)
	// Fetch a record by id
	// (GET /v1/records/{id})
	GetRecord(c *gin.Context, id string)
	// Pull record changes
	// (GET /v1/sync)
	PullSync(c *gin.Context, params PullSyncParams)
	// Push record changes
	// (POST /v1/sync)
	PushSync(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Register(c)
}

// Validate operation middleware
func (siw *ServerInterfaceWrapper) Validate(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Validate(c)
}

// ListRecords operation middleware
func (siw *ServerInterfaceWrapper) ListRecords(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRecordsParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", c.Request.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter type: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", c.Request.URL.Query(), &params.Tag)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tag: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, false, "query", c.Request.URL.Query(), &params.Query)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter query: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRecords(c, params)
}

// UpsertRecord operation middleware
func (siw *ServerInterfaceWrapper) UpsertRecord(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpsertRecord(c)
}

// DeleteRecord operation middleware
func (siw *ServerInterfaceWrapper) DeleteRecord(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteRecord(c, id)
}

// GetRecord operation middleware
func (siw *ServerInterfaceWrapper) GetRecord(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRecord(c, id)
}

// PullSync operation middleware
func (siw *ServerInterfaceWrapper) PullSync(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PullSyncParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PullSync(c, params)
}

// PushSync operation middleware
func (siw *ServerInterfaceWrapper) PushSync(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PushSync(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/v1/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/v1/auth/register", wrapper.Register)
	router.GET(options.BaseURL+"/v1/auth/validate", wrapper.Validate)
	router.GET(options.BaseURL+"/v1/records", wrapper.ListRecords)
	router.POST(options.BaseURL+"/v1/records", wrapper.UpsertRecord)
	router.DELETE(options.BaseURL+"/v1/records/:id", wrapper.DeleteRecord)
	router.GET(options.BaseURL+"/v1/records/:id", wrapper.GetRecord)
	router.GET(options.BaseURL+"/v1/sync", wrapper.PullSync)
	router.POST(options.BaseURL+"/v1/sync", wrapper.PushSync)
}
